---
name: auto-release

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

  workflow_call:
    secrets:
      ACCESS_TOKEN:
        required: true

jobs:
  auto-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-documentation:
    needs: [auto-release]
    uses: "./.github/workflows/build-documentation.yml"

  delete-old-releases:
    needs: [auto-release]
    uses: "./.github/workflows/delete-old-releases.yml"
    with:
      keep_latest: 1
