---
name: github-action-checker
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

  workflow_call:

jobs:
  github-action-chekcer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - uses: actions/setup-go@v4
        with:
          go-version: stable
          check-latest: true

      - name: Install Actionlint
        run: |
          go install github.com/rhysd/actionlint/cmd/actionlint@latest
        shell: dash -e {0}

      - name: Github Action Check
        run: actionlint
        shell: dash -e {0}
