---
name: link-checker

on:
  workflow_run:
    workflows: [pages-build-deployment]
    types:
      - completed

jobs:
  linkchecker:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Python Cache
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install Link Checker
        run: pip3 install linkchecker
        shell: dash -e {0}

      - name: Run Link Checker
        run: linkchecker --check-extern https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/
        shell: dash -e {0}
